// This file is auto-generated by @hey-api/openapi-ts

/**
 * Body_upload_workspace_file_api_workspace__path__post
 */
export type BodyUploadWorkspaceFileApiWorkspacePathPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * CreateTaskRequest
 * Create task request model
 */
export type CreateTaskRequest = {
    /**
     * Task Id
     * Task ID
     */
    task_id: string;
    /**
     * LLM configuration
     */
    llm_config: LlmConfig;
    /**
     * Should Plan
     * Whether to use planning mode
     */
    should_plan?: boolean;
    /**
     * Prompt
     * Task prompt
     */
    prompt: string;
    /**
     * Tools
     * List of tool names or MCP configs
     */
    tools?: Array<string> | null;
    /**
     * Files
     * Files to upload
     */
    files?: Array<FileData> | null;
};

/**
 * CreateTaskResponse
 * Create task response model
 */
export type CreateTaskResponse = {
    /**
     * Task Id
     */
    task_id: string;
};

/**
 * FileData
 * File data model for create task request
 */
export type FileData = {
    /**
     * Name
     * File name
     */
    name: string;
    /**
     * Content
     * Base64 encoded file content
     */
    content?: string | null;
    /**
     * Url
     * URL to download file from
     */
    url?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * InstallCustomToolRequest
 */
export type InstallCustomToolRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Config
     */
    config: string;
};

/**
 * InstallToolRequest
 */
export type InstallToolRequest = {
    /**
     * Toolid
     */
    toolId: string;
    /**
     * Env
     */
    env: {
        [key: string]: string;
    };
};

/**
 * LLMConfig
 */
export type LlmConfig = {
    /**
     * Modelid
     */
    modelId: string;
};

/**
 * LlmConfigRequest
 */
export type LlmConfigRequest = {
    /**
     * Id
     */
    id?: string | null;
    /**
     * Model
     */
    model: string;
    /**
     * Apikey
     */
    apiKey: string;
    /**
     * Baseurl
     */
    baseUrl: string;
    /**
     * Maxtokens
     */
    maxTokens: number;
    /**
     * Temperature
     */
    temperature: number;
    /**
     * Apitype
     */
    apiType: string;
};

/**
 * LlmConfigResponse
 */
export type LlmConfigResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Type
     */
    type: string;
    /**
     * Model
     */
    model: string;
    /**
     * Baseurl
     */
    baseUrl: string;
    /**
     * Apikey
     */
    apiKey: string;
    /**
     * Maxtokens
     */
    maxTokens: number;
    /**
     * Maxinputtokens
     */
    maxInputTokens: number | null;
    /**
     * Temperature
     */
    temperature: number;
    /**
     * Apitype
     */
    apiType: string;
    /**
     * Apiversion
     */
    apiVersion: string | null;
    /**
     * Isactive
     */
    isActive: boolean;
    /**
     * Createdat
     */
    createdAt: string;
    /**
     * Updatedat
     */
    updatedAt: string;
    /**
     * Organizationid
     */
    organizationId: string;
    /**
     * Name
     */
    name: string | null;
};

/**
 * ModifyPasswordRequest
 */
export type ModifyPasswordRequest = {
    /**
     * Old Password
     */
    old_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * ModifyPasswordResponse
 */
export type ModifyPasswordResponse = {
    /**
     * Message
     */
    message: string;
};

/**
 * PaginatedTasksResponse
 * Paginated tasks response model
 */
export type PaginatedTasksResponse = {
    /**
     * Tasks
     */
    tasks: Array<TaskResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
};

/**
 * PreferencesRequest
 */
export type PreferencesRequest = {
    /**
     * Language
     */
    language?: string | null;
};

/**
 * PreferencesResponse
 */
export type PreferencesResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Organizationid
     */
    organizationId: string;
    /**
     * Language
     */
    language: string | null;
    /**
     * Createdat
     */
    createdAt: string;
    /**
     * Updatedat
     */
    updatedAt: string;
};

/**
 * RegisterToolRequest
 */
export type RegisterToolRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    /**
     * Repourl
     */
    repoUrl?: string | null;
    /**
     * Command
     */
    command: string;
    /**
     * Args
     */
    args: Array<string>;
    /**
     * Envschema
     */
    envSchema: {
        [key: string]: unknown;
    };
};

/**
 * ShareTaskRequest
 * Share task request model
 */
export type ShareTaskRequest = {
    /**
     * Expires At
     */
    expires_at: number;
};

/**
 * ShareTaskResponse
 * Share task response model
 */
export type ShareTaskResponse = {
    /**
     * Message
     */
    message: string;
    /**
     * Task Id
     */
    task_id: string;
};

/**
 * SharedTaskResponse
 * Response model for shared task with progresses
 */
export type SharedTaskResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Organizationid
     */
    organizationId: string;
    /**
     * Outid
     */
    outId: string | null;
    /**
     * Llmid
     */
    llmId: string;
    /**
     * Summary
     */
    summary: string | null;
    /**
     * Prompt
     */
    prompt: string;
    /**
     * Status
     */
    status: string;
    /**
     * Tools
     */
    tools: {
        [key: string]: unknown;
    };
    /**
     * Shareexpiresat
     */
    shareExpiresAt: string | null;
    /**
     * Createdat
     */
    createdAt: string;
    /**
     * Updatedat
     */
    updatedAt: string;
    /**
     * Progresses
     */
    progresses: Array<TaskProgresses>;
};

/**
 * SigninData
 */
export type SigninData = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * SigninResponse
 */
export type SigninResponse = {
    /**
     * Token
     */
    token: string;
};

/**
 * SignupData
 */
export type SignupData = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Name
     */
    name: string;
    /**
     * Organizationname
     */
    organizationName: string;
};

/**
 * SignupResponse
 */
export type SignupResponse = {
    /**
     * Message
     */
    message: string;
};

/**
 * TaskProgresses
 * TaskProgresses table model
 */
export type TaskProgresses = {
    /**
     * Id
     */
    id?: string;
    /**
     * Createdat
     */
    createdAt?: string;
    /**
     * Updatedat
     */
    updatedAt?: string;
    /**
     * Organizationid
     */
    organizationId: string;
    /**
     * Taskid
     */
    taskId: string;
    /**
     * Index
     */
    index: number;
    /**
     * Round
     */
    round?: number;
    /**
     * Step
     */
    step: number;
    /**
     * Type
     */
    type: string;
    /**
     * Content
     */
    content: {
        [key: string]: unknown;
    };
};

/**
 * TaskResponse
 * Task response model
 */
export type TaskResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Organizationid
     */
    organizationId: string;
    /**
     * Outid
     */
    outId: string | null;
    /**
     * Llmid
     */
    llmId: string;
    /**
     * Summary
     */
    summary: string | null;
    /**
     * Prompt
     */
    prompt: string;
    /**
     * Status
     */
    status: string;
    /**
     * Tools
     */
    tools: Array<string | {
        [key: string]: unknown;
    }>;
    /**
     * Shareexpiresat
     */
    shareExpiresAt: string | null;
    /**
     * Createdat
     */
    createdAt: string;
    /**
     * Updatedat
     */
    updatedAt: string;
};

/**
 * TerminateTaskResponse
 * Terminate task response model
 */
export type TerminateTaskResponse = {
    /**
     * Message
     */
    message: string;
    /**
     * Task Id
     */
    task_id: string;
};

/**
 * ToolInfo
 */
export type ToolInfo = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Type
     */
    type: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Parameters
     */
    parameters: {
        [key: string]: unknown;
    } | null;
    /**
     * Source
     */
    source: string;
    /**
     * Schema
     */
    schema?: {
        [key: string]: unknown;
    } | null;
};

/**
 * ToolSchemaResponse
 */
export type ToolSchemaResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Repourl
     */
    repoUrl: string | null;
    /**
     * Command
     */
    command: string;
    /**
     * Args
     */
    args: Array<string>;
    /**
     * Envschema
     */
    envSchema: {
        [key: string]: unknown;
    };
    /**
     * Url
     */
    url: string;
    /**
     * Queryschema
     */
    querySchema: {
        [key: string]: unknown;
    };
    /**
     * Headersschema
     */
    headersSchema: {
        [key: string]: unknown;
    };
    /**
     * Createdat
     */
    createdAt: string;
    /**
     * Updatedat
     */
    updatedAt: string;
};

/**
 * UserInfoResponse
 */
export type UserInfoResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Name
     */
    name: string | null;
    /**
     * Organization Id
     */
    organization_id: string;
    /**
     * Organization Name
     */
    organization_name: string;
    /**
     * Is Root
     */
    is_root: boolean;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type SigninApiAuthSigninPostData = {
    body: SigninData;
    path?: never;
    query?: never;
    url: '/api/auth/signin';
};

export type SigninApiAuthSigninPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SigninApiAuthSigninPostError = SigninApiAuthSigninPostErrors[keyof SigninApiAuthSigninPostErrors];

export type SigninApiAuthSigninPostResponses = {
    /**
     * Successful Response
     */
    200: SigninResponse;
};

export type SigninApiAuthSigninPostResponse = SigninApiAuthSigninPostResponses[keyof SigninApiAuthSigninPostResponses];

export type SignupApiAuthSignupPostData = {
    body: SignupData;
    path?: never;
    query?: never;
    url: '/api/auth/signup';
};

export type SignupApiAuthSignupPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SignupApiAuthSignupPostError = SignupApiAuthSignupPostErrors[keyof SignupApiAuthSignupPostErrors];

export type SignupApiAuthSignupPostResponses = {
    /**
     * Successful Response
     */
    200: SignupResponse;
};

export type SignupApiAuthSignupPostResponse = SignupApiAuthSignupPostResponses[keyof SignupApiAuthSignupPostResponses];

export type GetLlmConfigsApiConfigLlmGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/config/llm';
};

export type GetLlmConfigsApiConfigLlmGetResponses = {
    /**
     * Response Get Llm Configs Api Config Llm Get
     * Successful Response
     */
    200: Array<LlmConfigResponse>;
};

export type GetLlmConfigsApiConfigLlmGetResponse = GetLlmConfigsApiConfigLlmGetResponses[keyof GetLlmConfigsApiConfigLlmGetResponses];

export type UpdateLlmConfigApiConfigLlmPostData = {
    body: LlmConfigRequest;
    path?: never;
    query?: never;
    url: '/api/config/llm';
};

export type UpdateLlmConfigApiConfigLlmPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateLlmConfigApiConfigLlmPostError = UpdateLlmConfigApiConfigLlmPostErrors[keyof UpdateLlmConfigApiConfigLlmPostErrors];

export type UpdateLlmConfigApiConfigLlmPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RemoveLlmConfigApiConfigLlmConfigIdDeleteData = {
    body?: never;
    path: {
        /**
         * Config Id
         */
        config_id: string;
    };
    query?: never;
    url: '/api/config/llm/{config_id}';
};

export type RemoveLlmConfigApiConfigLlmConfigIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RemoveLlmConfigApiConfigLlmConfigIdDeleteError = RemoveLlmConfigApiConfigLlmConfigIdDeleteErrors[keyof RemoveLlmConfigApiConfigLlmConfigIdDeleteErrors];

export type RemoveLlmConfigApiConfigLlmConfigIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetPreferencesApiConfigPreferencesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/config/preferences';
};

export type GetPreferencesApiConfigPreferencesGetResponses = {
    /**
     * Response Get Preferences Api Config Preferences Get
     * Successful Response
     */
    200: PreferencesResponse | null;
};

export type GetPreferencesApiConfigPreferencesGetResponse = GetPreferencesApiConfigPreferencesGetResponses[keyof GetPreferencesApiConfigPreferencesGetResponses];

export type UpdatePreferencesApiConfigPreferencesPostData = {
    body: PreferencesRequest;
    path?: never;
    query?: never;
    url: '/api/config/preferences';
};

export type UpdatePreferencesApiConfigPreferencesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePreferencesApiConfigPreferencesPostError = UpdatePreferencesApiConfigPreferencesPostErrors[keyof UpdatePreferencesApiConfigPreferencesPostErrors];

export type UpdatePreferencesApiConfigPreferencesPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ModifyPasswordApiMePasswordPostData = {
    body: ModifyPasswordRequest;
    path?: never;
    query?: never;
    url: '/api/me/password';
};

export type ModifyPasswordApiMePasswordPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ModifyPasswordApiMePasswordPostError = ModifyPasswordApiMePasswordPostErrors[keyof ModifyPasswordApiMePasswordPostErrors];

export type ModifyPasswordApiMePasswordPostResponses = {
    /**
     * Successful Response
     */
    200: ModifyPasswordResponse;
};

export type ModifyPasswordApiMePasswordPostResponse = ModifyPasswordApiMePasswordPostResponses[keyof ModifyPasswordApiMePasswordPostResponses];

export type GetMeApiMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/me';
};

export type GetMeApiMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserInfoResponse;
};

export type GetMeApiMeGetResponse = GetMeApiMeGetResponses[keyof GetMeApiMeGetResponses];

export type ListAgentToolsApiToolsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tools';
};

export type ListAgentToolsApiToolsGetResponses = {
    /**
     * Response List Agent Tools Api Tools Get
     * Successful Response
     */
    200: Array<ToolInfo>;
};

export type ListAgentToolsApiToolsGetResponse = ListAgentToolsApiToolsGetResponses[keyof ListAgentToolsApiToolsGetResponses];

export type InstallToolApiToolsInstallPostData = {
    body: InstallToolRequest;
    path?: never;
    query?: never;
    url: '/api/tools/install';
};

export type InstallToolApiToolsInstallPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type InstallToolApiToolsInstallPostError = InstallToolApiToolsInstallPostErrors[keyof InstallToolApiToolsInstallPostErrors];

export type InstallToolApiToolsInstallPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type InstallCustomToolApiToolsInstallCustomPostData = {
    body: InstallCustomToolRequest;
    path?: never;
    query?: never;
    url: '/api/tools/install/custom';
};

export type InstallCustomToolApiToolsInstallCustomPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type InstallCustomToolApiToolsInstallCustomPostError = InstallCustomToolApiToolsInstallCustomPostErrors[keyof InstallCustomToolApiToolsInstallCustomPostErrors];

export type InstallCustomToolApiToolsInstallCustomPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RemoveToolApiToolsToolIdDeleteData = {
    body?: never;
    path: {
        /**
         * Tool Id
         */
        tool_id: string;
    };
    query?: never;
    url: '/api/tools/{tool_id}';
};

export type RemoveToolApiToolsToolIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RemoveToolApiToolsToolIdDeleteError = RemoveToolApiToolsToolIdDeleteErrors[keyof RemoveToolApiToolsToolIdDeleteErrors];

export type RemoveToolApiToolsToolIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListToolSchemasApiToolsSchemasGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tools/schemas';
};

export type ListToolSchemasApiToolsSchemasGetResponses = {
    /**
     * Response List Tool Schemas Api Tools Schemas Get
     * Successful Response
     */
    200: Array<ToolSchemaResponse>;
};

export type ListToolSchemasApiToolsSchemasGetResponse = ListToolSchemasApiToolsSchemasGetResponses[keyof ListToolSchemasApiToolsSchemasGetResponses];

export type RegisterToolApiToolsRegisterPostData = {
    body: RegisterToolRequest;
    path?: never;
    query?: never;
    url: '/api/tools/register';
};

export type RegisterToolApiToolsRegisterPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterToolApiToolsRegisterPostError = RegisterToolApiToolsRegisterPostErrors[keyof RegisterToolApiToolsRegisterPostErrors];

export type RegisterToolApiToolsRegisterPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetSharedTaskApiSharedTasksTaskIdGetData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/shared_tasks/{task_id}';
};

export type GetSharedTaskApiSharedTasksTaskIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSharedTaskApiSharedTasksTaskIdGetError = GetSharedTaskApiSharedTasksTaskIdGetErrors[keyof GetSharedTaskApiSharedTasksTaskIdGetErrors];

export type GetSharedTaskApiSharedTasksTaskIdGetResponses = {
    /**
     * Successful Response
     */
    200: SharedTaskResponse;
};

export type GetSharedTaskApiSharedTasksTaskIdGetResponse = GetSharedTaskApiSharedTasksTaskIdGetResponses[keyof GetSharedTaskApiSharedTasksTaskIdGetResponses];

export type GetTasksPaginatedApiTasksGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/tasks';
};

export type GetTasksPaginatedApiTasksGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTasksPaginatedApiTasksGetError = GetTasksPaginatedApiTasksGetErrors[keyof GetTasksPaginatedApiTasksGetErrors];

export type GetTasksPaginatedApiTasksGetResponses = {
    /**
     * Successful Response
     */
    200: PaginatedTasksResponse;
};

export type GetTasksPaginatedApiTasksGetResponse = GetTasksPaginatedApiTasksGetResponses[keyof GetTasksPaginatedApiTasksGetResponses];

export type CreateTaskApiTasksPostData = {
    body: CreateTaskRequest;
    path?: never;
    query?: never;
    url: '/api/tasks';
};

export type CreateTaskApiTasksPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTaskApiTasksPostError = CreateTaskApiTasksPostErrors[keyof CreateTaskApiTasksPostErrors];

export type CreateTaskApiTasksPostResponses = {
    /**
     * Successful Response
     */
    200: CreateTaskResponse;
};

export type CreateTaskApiTasksPostResponse = CreateTaskApiTasksPostResponses[keyof CreateTaskApiTasksPostResponses];

export type GetTaskApiTasksTaskIdGetData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/tasks/{task_id}';
};

export type GetTaskApiTasksTaskIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTaskApiTasksTaskIdGetError = GetTaskApiTasksTaskIdGetErrors[keyof GetTaskApiTasksTaskIdGetErrors];

export type GetTaskApiTasksTaskIdGetResponses = {
    /**
     * Successful Response
     */
    200: TaskResponse;
};

export type GetTaskApiTasksTaskIdGetResponse = GetTaskApiTasksTaskIdGetResponses[keyof GetTaskApiTasksTaskIdGetResponses];

export type TaskEventsApiTasksTaskIdEventsGetData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/tasks/{task_id}/events';
};

export type TaskEventsApiTasksTaskIdEventsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TaskEventsApiTasksTaskIdEventsGetError = TaskEventsApiTasksTaskIdEventsGetErrors[keyof TaskEventsApiTasksTaskIdEventsGetErrors];

export type TaskEventsApiTasksTaskIdEventsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type TerminateTaskApiTasksTaskIdTerminatePostData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/tasks/{task_id}/terminate';
};

export type TerminateTaskApiTasksTaskIdTerminatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TerminateTaskApiTasksTaskIdTerminatePostError = TerminateTaskApiTasksTaskIdTerminatePostErrors[keyof TerminateTaskApiTasksTaskIdTerminatePostErrors];

export type TerminateTaskApiTasksTaskIdTerminatePostResponses = {
    /**
     * Successful Response
     */
    200: TerminateTaskResponse;
};

export type TerminateTaskApiTasksTaskIdTerminatePostResponse = TerminateTaskApiTasksTaskIdTerminatePostResponses[keyof TerminateTaskApiTasksTaskIdTerminatePostResponses];

export type ShareTaskApiTasksTaskIdSharePostData = {
    body: ShareTaskRequest;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/tasks/{task_id}/share';
};

export type ShareTaskApiTasksTaskIdSharePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ShareTaskApiTasksTaskIdSharePostError = ShareTaskApiTasksTaskIdSharePostErrors[keyof ShareTaskApiTasksTaskIdSharePostErrors];

export type ShareTaskApiTasksTaskIdSharePostResponses = {
    /**
     * Successful Response
     */
    200: ShareTaskResponse;
};

export type ShareTaskApiTasksTaskIdSharePostResponse = ShareTaskApiTasksTaskIdSharePostResponses[keyof ShareTaskApiTasksTaskIdSharePostResponses];

export type DeleteWorkspaceFileApiWorkspacePathDeleteData = {
    body?: never;
    path: {
        /**
         * Path
         */
        path: string;
    };
    query?: never;
    url: '/api/workspace/{path}';
};

export type DeleteWorkspaceFileApiWorkspacePathDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteWorkspaceFileApiWorkspacePathDeleteError = DeleteWorkspaceFileApiWorkspacePathDeleteErrors[keyof DeleteWorkspaceFileApiWorkspacePathDeleteErrors];

export type DeleteWorkspaceFileApiWorkspacePathDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetWorkspaceFileApiWorkspacePathGetData = {
    body?: never;
    path: {
        /**
         * Path
         */
        path: string;
    };
    query?: never;
    url: '/api/workspace/{path}';
};

export type GetWorkspaceFileApiWorkspacePathGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetWorkspaceFileApiWorkspacePathGetError = GetWorkspaceFileApiWorkspacePathGetErrors[keyof GetWorkspaceFileApiWorkspacePathGetErrors];

export type GetWorkspaceFileApiWorkspacePathGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UploadWorkspaceFileApiWorkspacePathPostData = {
    body: BodyUploadWorkspaceFileApiWorkspacePathPost;
    path: {
        /**
         * Path
         */
        path: string;
    };
    query?: never;
    url: '/api/workspace/{path}';
};

export type UploadWorkspaceFileApiWorkspacePathPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadWorkspaceFileApiWorkspacePathPostError = UploadWorkspaceFileApiWorkspacePathPostErrors[keyof UploadWorkspaceFileApiWorkspacePathPostErrors];

export type UploadWorkspaceFileApiWorkspacePathPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DownloadWorkspaceFileApiWorkspaceDownloadPathGetData = {
    body?: never;
    path: {
        /**
         * Path
         */
        path: string;
    };
    query?: never;
    url: '/api/workspace/download/{path}';
};

export type DownloadWorkspaceFileApiWorkspaceDownloadPathGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DownloadWorkspaceFileApiWorkspaceDownloadPathGetError = DownloadWorkspaceFileApiWorkspaceDownloadPathGetErrors[keyof DownloadWorkspaceFileApiWorkspaceDownloadPathGetErrors];

export type DownloadWorkspaceFileApiWorkspaceDownloadPathGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'http://localhost:5172' | (string & {});
};