import { ModelDefinition } from './models/types';

export const modelDefinitions: ModelDefinition[] = [
  {
    id: 'claude-3-5-sonnet',
    name: 'Claude 3.5 Sonnet',
    description: 'Anthropic 最智能的模型',
    providerId: 'vercel',
    providerModelId: 'anthropic/claude-3.5-sonnet',
    adapterType: 'openai',
    contextLength: 200000,
    capabilities: { streaming: true, tools: true, vision: true, audio: false },
    inputModalities: ['text', 'image'],
    outputModalities: ['text'],
    pricing: { input: 3, output: 15, currency: 'USD' },
    supportedParameters: ['temperature', 'top_p', 'max_tokens', 'tools'],
    family: 'claude',
    tags: ['smart', 'long-context'],
  },
  {
    id: 'deepseek-chat',
    name: 'DeepSeek Chat',
    description: 'DeepSeek V3 强大的对话模型',
    providerId: 'vercel',
    providerModelId: 'deepseek/deepseek-v3.2-exp',
    adapterType: 'openai',
    contextLength: 64000,
    capabilities: { streaming: true, tools: false, vision: false, audio: false },
    inputModalities: ['text'],
    outputModalities: ['text'],
    pricing: { input: 0.14, output: 0.28, currency: 'USD' },
    supportedParameters: ['temperature', 'top_p', 'max_tokens'],
    family: 'deepseek',
    tags: ['affordable', 'chinese'],
  },
  {
    id: 'deepseek-reasoner',
    name: 'DeepSeek Reasoner',
    description: 'DeepSeek R1 推理模型',
    providerId: 'vercel',
    providerModelId: 'deepseek/deepseek-v3.2-exp-thinking',
    adapterType: 'openai',
    contextLength: 64000,
    capabilities: { streaming: true, tools: false, vision: false, audio: false },
    inputModalities: ['text'],
    outputModalities: ['text'],
    pricing: { input: 0.55, output: 2.19, currency: 'USD' },
    supportedParameters: ['temperature', 'top_p', 'max_tokens'],
    family: 'deepseek',
    tags: ['reasoning', 'chinese'],
  },
];
