import { ModelInfo } from './models/types';

export const modelDefinitions: ModelInfo[] = [
  {
    id: 'xai/grok-4',
    name: 'Grok 4',
    description: 'Grok 的最新模型',
    provider: 'vercel',
    family: 'xai',
    type: 'language',
    contextLength: 200000,
    supportsStreaming: true,
    supportsFunctionCalling: true,
    supportsVision: true,
    pricing: { input: 3, output: 15, currency: 'USD' },
    enabled: false,
    metadata: {
      providerId: 'vercel',
      providerModelId: 'xai/grok-4',
      adapterType: 'openai',
      inputModalities: ['text', 'image'],
      outputModalities: ['text'],
      supportedParameters: ['temperature', 'top_p', 'max_tokens', 'tools'],
    },
  },
  {
    id: 'anthropic/claude-sonnet-4.5',
    name: 'Anthropic Claude Sonnet 4.5',
    description: 'Anthropic 的最新模型',
    provider: 'vercel',
    family: 'anthropic',
    type: 'language',
    contextLength: 200000,
    supportsStreaming: true,
    supportsFunctionCalling: true,
    supportsVision: true,
    pricing: { input: 3, output: 15, currency: 'USD' },
    enabled: false,
    metadata: {
      providerId: 'vercel',
      providerModelId: 'anthropic/claude-sonnet-4.5',
      adapterType: 'openai',
      inputModalities: ['text', 'image'],
      outputModalities: ['text'],
      supportedParameters: ['temperature', 'top_p', 'max_tokens', 'tools'],
    },
  },
  {
    id: 'claude-3-5-sonnet',
    name: 'Claude 3.5 Sonnet',
    description: 'Anthropic 最智能的模型',
    provider: 'vercel',
    family: 'claude',
    type: 'language',
    contextLength: 200000,
    supportsStreaming: true,
    supportsFunctionCalling: true,
    supportsVision: true,
    pricing: { input: 3, output: 15, currency: 'USD' },
    enabled: false,
    metadata: {
      providerId: 'vercel',
      providerModelId: 'anthropic/claude-3.5-sonnet',
      adapterType: 'openai',
      inputModalities: ['text', 'image'],
      outputModalities: ['text'],
      supportedParameters: ['temperature', 'top_p', 'max_tokens', 'tools'],
    },
  },
  {
    id: 'deepseek-chat',
    name: 'DeepSeek Chat',
    description: 'DeepSeek V3 强大的对话模型',
    provider: 'vercel',
    family: 'deepseek',
    type: 'language',
    contextLength: 64000,
    supportsStreaming: true,
    supportsFunctionCalling: false,
    supportsVision: false,
    pricing: { input: 0.14, output: 0.28, currency: 'USD' },
    enabled: false,
    metadata: {
      providerId: 'vercel',
      providerModelId: 'deepseek/deepseek-v3.2-exp',
      adapterType: 'openai',
      inputModalities: ['text'],
      outputModalities: ['text'],
      supportedParameters: ['temperature', 'top_p', 'max_tokens'],
    },
  },
  {
    id: 'deepseek-reasoner',
    name: 'DeepSeek Reasoner',
    description: 'DeepSeek R1 推理模型',
    provider: 'vercel',
    family: 'deepseek',
    type: 'language',
    contextLength: 64000,
    supportsStreaming: true,
    supportsFunctionCalling: false,
    supportsVision: false,
    pricing: { input: 0.55, output: 2.19, currency: 'USD' },
    enabled: false,
    metadata: {
      providerId: 'vercel',
      providerModelId: 'deepseek/deepseek-v3.2-exp-thinking',
      adapterType: 'openai',
      inputModalities: ['text'],
      outputModalities: ['text'],
      supportedParameters: ['temperature', 'top_p', 'max_tokens'],
    },
  },
  {
    id: 'openai/text-embedding-3-large',
    name: 'text-embedding-3-large',
    description: "OpenAI's most capable embedding model for both english and non-english tasks.",
    provider: 'vercel',
    family: 'openai',
    type: 'embedding',
    contextLength: 0,
    supportsStreaming: false,
    supportsFunctionCalling: false,
    supportsVision: false,
    pricing: { input: 0.00000013, currency: 'USD' },
    enabled: false,
  },
  {
    id: 'openai/text-embedding-3-small',
    name: 'text-embedding-3-small',
    description: "OpenAI's improved, more performant version of their ada embedding model.",
    provider: 'vercel',
    family: 'openai',
    type: 'embedding',
    contextLength: 0,
    supportsStreaming: false,
    supportsFunctionCalling: false,
    supportsVision: false,
    pricing: { input: 0.00000002, currency: 'USD' },
    enabled: false,
  },
];
